#!/usr/bin/env python3
# quilttools_fpp_eq_export.py
# Module 6 of the Quilt Tools FPP suite.
#
# Exports the current FPP block as an Electric Quilt EasyDraw project file
# (.pj6 / .pj8) that can be opened directly in EQ6 or EQ8.
#
# Format reverse-engineered from real Quilt Assistant output and validated
# byte-for-byte against HalfSquarevariation.pj6 and HalfSquarevariation.PJ8.
#
# Layout summary (data blob starts at file offset 0x90 in PJ6, 0xc0 in PJ8):
#   +0x00  10020000 05f20180 43000000     (12 fixed bytes)
#   +0x0c  node_count uint16, node_count uint16  (stored twice)
#   +0x10  line_count uint16, 0x0000
#   +0x14  00000400 00000100               (8 fixed bytes)
#   +0x1c  block_width   uint32 in PJ6, float32 in PJ8  (600 = 6.00 inches)
#   +0x20  block_height  same encoding
#   +0x24  patch_count   uint32
#   +0x28  16 zero bytes
#   +0x38  'BLOK' + 00000000  (8 bytes)
#   +0x40  LINE TABLE: line_count x 8 bytes (x1, y1, x2, y2 as uint16 LE)
#            coordinate range 0-20160 = full block
#            raw = round(normalized * 20160), normalized = px / block_px
#   then   patch-extra zeros + 16-byte sentinel (ba00 4e×6 + zeros)
#   then   name block: 4-byte prefix + UTF-16LE null-terminated, uint32-aligned
#   then   description block: same structure
#   then   4 x 28-byte colour entries (fixed)

import inkex
import struct
import math
import os

import quilttools_fpp_core as core


PX_PER_INCH  = 96.0
EQ_MAX_COORD = 20160


# --- Fixed binary templates ---------------------------------------------

# PJ6 header (0x00-0x8f = 144 bytes).
# Slots 0x38-0x77 are file_end (patched at write time, zeroed in template).
PJ6_HEADER_TEMPLATE = bytearray(bytes.fromhex(
    "45512d504a360000"   # 0x00  EQ-PJ6\0\0
    "78000000"           # 0x08  version_block offset = 0x78
    "00000000"           # 0x0c  reserved
    "84000000" "01000000"  # 0x10
    "84000000" "02000000"  # 0x18
    "8c000000" "03000000"  # 0x20
    "90000000" "00000000"  # 0x28  data_blob_start = 0x90
    "90000000" "01000000"  # 0x30
    + "0000000000000000" * 8  # 0x38-0x77  file_end slots
    + "49034551" "36212121" "21212e2e" "00030100" "f5deb300" "01000000"
))
assert len(PJ6_HEADER_TEMPLATE) == 0x90, len(PJ6_HEADER_TEMPLATE)

# PJ8 header (0x00-0xbf = 192 bytes, 48 bytes longer than PJ6).
PJ8_HEADER_TEMPLATE = bytearray(bytes.fromhex(
    "455138504a380000"   # 0x00  EQ8PJ8\0\0
    "a8000000"           # 0x08  version_block offset = 0xa8
    "00000000"           # 0x0c  reserved
    "b4000000" "01000000"
    "b4000000" "02000000"
    "bc000000" "03000000"
    "c0000000" "00000000"  # data_blob_start = 0xc0
    "c0000000" "01000000"
    + "0000000000000000" * 14  # 0x38-0xa7  file_end slots
    + "49034551" "3821213a" "2d292e2e" "00030100" "f5deb300" "01000000"
))
assert len(PJ8_HEADER_TEMPLATE) == 0xc0, len(PJ8_HEADER_TEMPLATE)

# Fixed bytes within the data-blob config region (at offsets relative to
# data-blob start, i.e. 0x90 for PJ6, 0xc0 for PJ8).
#
# Layout:
#   +0x00  data_blob_length uint32          (dynamic, file_size - blob_start)
#   +0x04  fixed 8 bytes                    DATA_BLOB_FIXED_A
#   +0x0c  node_count uint16, node_count uint16 (dynamic)
#   +0x10  line_count uint16, 0x0000         (dynamic)
#   +0x14  0x0000, patch_count uint16        (dynamic)
#   +0x18  fixed 4 bytes                    DATA_BLOB_FIXED_B (= 00 00 01 00)
#   +0x1c  block_width  (uint32 PJ6 / float32 PJ8)
#   +0x20  block_height (same)
#   +0x24  patch_count uint32
#   +0x28  16 zero bytes
#   +0x38  'BLOK' + 4 zero bytes            DATA_BLOB_BLOK
#   +0x40  line table (line_count × 8 bytes)
#   ...    patch_extra (patches + padding + sentinel + name + desc + colour tail)
DATA_BLOB_FIXED_A = bytes.fromhex("05f20180" "43000000")  # 8 bytes
DATA_BLOB_FIXED_B = bytes.fromhex("00000100")              # 4 bytes
DATA_BLOB_BLOK    = bytes.fromhex("424c4f4b" "00000000")

PATCH_SENTINEL = bytes.fromhex("ba00") + b"\x4e" * 6 + b"\x00" * 8

COLOUR_ENTRY = bytes.fromhex("01000000" "f5deb300") + b"\x00" * 20
COLOUR_TAIL  = COLOUR_ENTRY * 4


def norm_to_raw(v):
    """Normalised 0.0-1.0  ->  EQ integer 0-20160."""
    return round(float(v) * EQ_MAX_COORD)


def build_eq_file(lines_norm, block_w_in, block_h_in, block_name,
                  patches_norm=None,
                  patch_count=0,
                  description="Generated by Quilt Tools FPP",
                  target="pj6"):
    """
    Build a valid EQ EasyDraw project file.

    Parameters
    ----------
    lines_norm   : list of (x1, y1, x2, y2) — interior line segments,
                   coordinates normalised 0.0-1.0; block-perimeter edges excluded
    block_w_in   : float  finished block width in inches
    block_h_in   : float  finished block height in inches
    block_name   : str    name shown in EQ block library
    patches_norm : list of polygons (each = list of (x, y) tuples normalised 0-1)
                   one polygon per leaf region. EQ8 requires this — the file
                   will not load if this is empty when patch_count > 0.
    patch_count  : int    number of leaf regions (= len(patches_norm))
    description  : str    attribution / comment string
    target       : str    'pj6' (recommended) or 'pj8'

    Returns
    -------
    bytes  complete binary file ready to write
    """
    MAX     = EQ_MAX_COORD
    CORNERS = {(0, 0), (MAX, 0), (MAX, MAX), (0, MAX)}
    is_pj8  = (target.lower() == "pj8")

    # Count unique interior nodes (corners are implicit in EQ).
    # node_count = max(unique_interior_intersections, 3) — derived from
    # comparing QA-generated reference files (HST, HSV).
    interior = set()
    for x1, y1, x2, y2 in lines_norm:
        for xn, yn in [(x1, y1), (x2, y2)]:
            r = (norm_to_raw(xn), norm_to_raw(yn))
            if r not in CORNERS:
                interior.add(r)

    node_count  = max(len(interior), 3)
    line_count  = len(lines_norm)
    block_w_hu  = round(block_w_in * 100)   # hundredths of inch
    block_h_hu  = round(block_h_in * 100)

    # Line records
    line_bytes = b""
    for x1, y1, x2, y2 in lines_norm:
        line_bytes += struct.pack(
            "<4H",
            norm_to_raw(x1), norm_to_raw(y1),
            norm_to_raw(x2), norm_to_raw(y2),
        )

    # Patch-extra: REAL patch geometry (not optional — EQ8 requires this).
    # Format reverse-engineered from QA reference files:
    #   uint16(0) uint16(1)              <- patch list header
    #   uint16(i) for i in range(2, patch_count)   <- META INDEX LIST
    #                                     One uint16 per patch beyond the
    #                                     first two, valued 2, 3, 4, ...,
    #                                     patch_count-1. So:
    #                                       2 patches → no meta
    #                                       3 patches → uint16(2)
    #                                       4 patches → uint16(2), uint16(3)
    #                                       N patches → 2, 3, ..., N-1
    #                                     Empirically derived from HST
    #                                     (2 patches), Three_Piece (3),
    #                                     Four_Piece (4), HSV (4) reference
    #                                     files. Without this prefix EQ8
    #                                     throws "out of memory" trying to
    #                                     parse the patch records.
    #   for each patch:
    #     uint16(1) uint16(vcount)       <- patch marker + vertex count
    #     vcount × (uint16(x), uint16(y))
    #   <variable padding zeros>
    #   8-byte sentinel + trailing zeros
    patch_extra_body = struct.pack("<HH", 0, 1)

    for i in range(2, patch_count):
        patch_extra_body += struct.pack("<H", i)

    if patches_norm:
        for poly in patches_norm:
            verts = list(poly)
            patch_extra_body += struct.pack("<HH", 1, len(verts))
            for x, y in verts:
                patch_extra_body += struct.pack("<2H",
                    norm_to_raw(x), norm_to_raw(y))

    # Pad with zeros (length matches what QA writes for the same line/patch count).
    # Empirically: QA writes ~20 bytes of zeros before the sentinel for HST,
    # and the sentinel sits at a position that makes the trailing block aligned.
    # We use 20 bytes as a safe default - EQ8 doesn't appear to care about exact
    # padding length so long as the sentinel is present.
    padding_bytes = 20

    patch_extra = patch_extra_body + b"\x00" * padding_bytes + PATCH_SENTINEL

    def encode_string(s):
        raw = s.encode("utf-16-le") + b"\x00\x00"
        while len(raw) % 4:
            raw += b"\x00"
        return b"\x00\x00\x00\x00" + raw

    # Assemble data blob.
    # The data_blob_length value at +0x00 must equal len(blob) — but len(blob)
    # depends on the rest of the assembly. We assemble everything AFTER the
    # length field first, then prepend the length once known.
    blob_after_length = bytearray()
    blob_after_length += DATA_BLOB_FIXED_A                                       # +0x04
    blob_after_length += struct.pack("<HH", node_count, node_count)              # +0x0c
    blob_after_length += struct.pack("<HH", line_count, 0)                       # +0x10
    blob_after_length += struct.pack("<HH", 0, patch_count)                      # +0x14
    blob_after_length += DATA_BLOB_FIXED_B                                       # +0x18

    # Block dimensions: PJ6 uint32, PJ8 float32 (same numeric value).
    if is_pj8:
        blob_after_length += struct.pack("<f", float(block_w_hu))                # +0x1c
        blob_after_length += struct.pack("<f", float(block_h_hu))                # +0x20
    else:
        blob_after_length += struct.pack("<I", block_w_hu)                       # +0x1c
        blob_after_length += struct.pack("<I", block_h_hu)                       # +0x20

    blob_after_length += struct.pack("<I", patch_count)                          # +0x24
    blob_after_length += b"\x00" * 16                                            # +0x28
    blob_after_length += DATA_BLOB_BLOK                                          # +0x38
    blob_after_length += line_bytes                                              # +0x40
    blob_after_length += patch_extra
    blob_after_length += encode_string(block_name)
    blob_after_length += encode_string(description)
    blob_after_length += COLOUR_TAIL

    # Total blob length = 4 bytes for the length field itself + everything after
    blob_length = 4 + len(blob_after_length)
    blob = bytearray()
    blob += struct.pack("<I", blob_length)                                       # +0x00
    blob += blob_after_length

    # Patch header: file_end = total file size, written into every file_end slot
    header          = bytearray(PJ8_HEADER_TEMPLATE if is_pj8 else PJ6_HEADER_TEMPLATE)
    data_blob_start = 0xc0 if is_pj8 else 0x90
    file_end        = data_blob_start + len(blob)
    slot_stop       = 0xa8 if is_pj8 else 0x78
    for slot in range(0x38, slot_stop, 8):
        struct.pack_into("<I", header, slot, file_end)

    return bytes(header) + bytes(blob)


def extract_lines_from_tree(tree, block_w_px, block_h_px):
    """
    Extract interior cut lines by collinear-segment clustering.

    Approach (purely geometric, ignores tree structure):
      1. Collect every interior edge from every leaf polygon.
         Edges where both endpoints sit on the block boundary are excluded.
      2. Group edges by the infinite line they lie on (quantised hash).
      3. Within each group, cluster edges that are adjacent or overlapping
         along the line direction. Each cluster = one logical cut line.
      4. Emit a normalised line spanning the extreme endpoints of each cluster.

    Why this beats tree-walking:
      The heal tool can corrupt the region tree (orphan subtrees, broken
      parent links, "cuts" with one child) but the leaf polygon geometry
      stays correct. Geometric extraction recovers every cut line that's
      visually present, even when the tree no longer records it.

    T-intersections (where one polygon's edge has been subdivided on the
    other side) are handled because all sub-segments still lie on the same
    infinite line and cluster together.
    """
    GAP_TOL = 2.0   # px: max gap along a line to consider two segments
                    #     part of the same logical cut

    def is_block_boundary_edge(a, b, w, h, tol=2.0):
        """True if both endpoints lie on the same side of the block."""
        ax, ay = a
        bx, by = b
        return (
            (ax < tol      and bx < tol)      or  # left edge
            (ax > w - tol  and bx > w - tol)  or  # right edge
            (ay < tol      and by < tol)      or  # top edge
            (ay > h - tol  and by > h - tol)      # bottom edge
        )

    def line_key(a, b):
        """Hashable key for the infinite line through a-b."""
        dx = b[0] - a[0]
        dy = b[1] - a[1]
        L = math.hypot(dx, dy)
        if L < 1e-6:
            return None
        nx, ny = dx / L, dy / L
        # Canonicalise direction: nx >= 0, or nx == 0 with ny >= 0
        if nx < 0 or (abs(nx) < 1e-9 and ny < 0):
            nx, ny = -nx, -ny
        # Signed perpendicular distance from origin
        c = -ny * a[0] + nx * a[1]
        # Quantise to ~1px to bucket near-collinear edges together
        return (round(nx, 3), round(ny, 3), round(c, 0))

    # Step 1: gather all unique interior edges across all leaf polygons.
    leaves         = [r for r in tree.regions.values() if not r.children]
    interior_edges = set()
    for r in leaves:
        n = len(r.polygon)
        for i in range(n):
            a = tuple(r.polygon[i])
            b = tuple(r.polygon[(i + 1) % n])
            if is_block_boundary_edge(a, b, block_w_px, block_h_px):
                continue
            # Canonicalise edge order so (a,b) and (b,a) collide
            key = tuple(sorted([
                (round(a[0], 2), round(a[1], 2)),
                (round(b[0], 2), round(b[1], 2)),
            ]))
            interior_edges.add(key)

    # Step 2: bucket edges by infinite-line key
    groups = {}
    for (a, b) in interior_edges:
        k = line_key(a, b)
        if k is None:
            continue
        groups.setdefault(k, []).append((a, b))

    # Step 3 & 4: within each group, merge adjacent edges into clusters
    output_lines = []
    for edges in groups.values():
        # Use the first edge's direction as the parametrisation reference
        a0, b0 = edges[0]
        dx, dy = b0[0] - a0[0], b0[1] - a0[1]
        L = math.hypot(dx, dy)
        if L < 1e-6:
            continue
        nx, ny = dx / L, dy / L

        # Compute (t_min, t_max) for each edge along this direction
        intervals = []
        for (a, b) in edges:
            ta = (a[0] - a0[0]) * nx + (a[1] - a0[1]) * ny
            tb = (b[0] - a0[0]) * nx + (b[1] - a0[1]) * ny
            intervals.append((min(ta, tb), max(ta, tb)))

        # Merge overlapping/adjacent intervals
        intervals.sort()
        cur_min, cur_max = intervals[0]
        clusters = []
        for tmin, tmax in intervals[1:]:
            if tmin <= cur_max + GAP_TOL:
                cur_max = max(cur_max, tmax)
            else:
                clusters.append((cur_min, cur_max))
                cur_min, cur_max = tmin, tmax
        clusters.append((cur_min, cur_max))

        # Emit one line per cluster
        for cmin, cmax in clusters:
            p0 = (a0[0] + nx * cmin, a0[1] + ny * cmin)
            p1 = (a0[0] + nx * cmax, a0[1] + ny * cmax)
            output_lines.append((
                p0[0] / block_w_px, p0[1] / block_h_px,
                p1[0] / block_w_px, p1[1] / block_h_px,
            ))

    return output_lines

# --- The Inkscape Extension ---------------------------------------------

class EQExportPlugin(inkex.Effect):

    def add_arguments(self, pars):
        pars.add_argument("--block_name",  type=str,   default="My FPP Block")
        pars.add_argument("--block_w_in",  type=float, default=6.0)
        pars.add_argument("--block_h_in",  type=float, default=6.0)
        pars.add_argument("--target",      type=str,   default="pj6")
        pars.add_argument("--output_path", type=str,   default="")

    def effect(self):
        g, block_data = core.find_fpp_group(self.svg)
        if g is None:
            return inkex.errormsg(
                "No Quilt Tools FPP block found.\n"
                "Please create and cut a block first using:\n"
                "  Extensions > Quilt Tools > 1. New Block\n"
                "  Extensions > Quilt Tools > 2. Guillotine Cut")

        tree = block_data.tree

        # ------------------------------------------------------------------
        # Determine block size.
        #
        # The block's true size lives in the SVG's geometry, not the dialog.
        # The dialog field used to control block size, but that caused
        # mismatches when the user's SVG was a different size than the
        # default 6" — vertices ended up scaled wrong and the block
        # appeared off-screen in EQ.
        #
        # New behaviour:
        #   1. Compute the actual block size from the FPP polygon data.
        #   2. Cross-check against the SVG's <svg width=...> attribute.
        #   3. Use the dialog values only if both are missing or inconsistent.
        # ------------------------------------------------------------------
        block_w_px, block_h_px = self._detect_block_size_px(tree)

        if block_w_px is None or block_h_px is None:
            # Couldn't auto-detect — fall back to dialog
            block_w_in = self.options.block_w_in
            block_h_in = self.options.block_h_in
            block_w_px = block_w_in * PX_PER_INCH
            block_h_px = block_h_in * PX_PER_INCH
            size_source = "dialog (auto-detect failed)"
        else:
            block_w_in = block_w_px / PX_PER_INCH
            block_h_in = block_h_px / PX_PER_INCH
            size_source = "auto-detected from block geometry"

        lines_norm = extract_lines_from_tree(tree, block_w_px, block_h_px)

        if not lines_norm:
            return inkex.errormsg(
                "No interior boundary lines found.\n"
                "The block needs at least one guillotine cut before export.")

        # Sanity check: all normalised coordinates must be in [0, 1]
        for x1, y1, x2, y2 in lines_norm:
            for v in (x1, y1, x2, y2):
                if v < -0.001 or v > 1.001:
                    return inkex.errormsg(
                        "Internal error: line coordinates out of range.\n"
                        "Block size detection produced normalised value {:.3f} "
                        "(must be 0-1).\n\n"
                        "Try entering an explicit block size in the dialog.".format(v))

        # Patch count = number of leaf regions
        leaves      = [r for r in tree.regions.values() if not r.children]
        patch_count = len(leaves)

        # Build patches_norm: each leaf region's polygon, normalised to 0-1.
        # EQ8 requires explicit patch geometry — without it the file fails
        # to load even though it has valid line data.
        patches_norm = []
        for region in leaves:
            poly_norm = []
            for x, y in region.polygon:
                poly_norm.append((x / block_w_px, y / block_h_px))
            patches_norm.append(poly_norm)

        target     = self.options.target.lower()
        ext        = ".pj8" if target == "pj8" else ".pj6"
        block_name = self.options.block_name.strip() or "FPP Block"

        # ------------------------------------------------------------------
        # Resolve output path explicitly.
        #
        # Priority:
        #   1. If the user typed a path and it's absolute -> use it directly.
        #   2. If the user typed a path that's relative -> join with their
        #      Documents folder (predictable; doesn't depend on Inkscape's
        #      working directory which varies wildly on Windows).
        #   3. If empty -> default to Documents/<block_name>.<ext>
        #
        # The SVG's docname is intentionally NOT used as a base anymore --
        # it gave inconsistent results when Inkscape was launched from
        # different places.
        # ------------------------------------------------------------------
        documents_dir = self._get_documents_dir()

        raw_out = self.options.output_path.strip()
        if raw_out:
            # User typed something. Treat as relative if not absolute.
            if os.path.isabs(raw_out):
                out_path = raw_out
            else:
                out_path = os.path.join(documents_dir, raw_out)
        else:
            # Default: Documents/<block_name>.<ext>
            safe_name = self._sanitise_filename(block_name)
            out_path  = os.path.join(documents_dir, safe_name + ext)

        # Make sure the extension matches the chosen format
        root, current_ext = os.path.splitext(out_path)
        if current_ext.lower() not in (".pj6", ".pj8"):
            out_path = out_path + ext
        elif current_ext.lower() != ext:
            out_path = root + ext

        # Make sure the directory exists
        out_dir = os.path.dirname(out_path)
        if out_dir and not os.path.isdir(out_dir):
            try:
                os.makedirs(out_dir, exist_ok=True)
            except Exception as e:
                return inkex.errormsg(
                    "Could not create output directory:\n  {dir}\n{err}\n\n"
                    "Try entering a full path in the dialog (e.g. "
                    "C:\\Users\\YourName\\Desktop\\block.pj6).".format(
                        dir=out_dir, err=str(e)))

        file_bytes = build_eq_file(
            lines_norm   = lines_norm,
            block_w_in   = block_w_in,
            block_h_in   = block_h_in,
            block_name   = block_name,
            patches_norm = patches_norm,
            patch_count  = patch_count,
            description  = "Generated by Quilt Tools FPP",
            target       = target,
        )

        try:
            with open(out_path, "wb") as f:
                f.write(file_bytes)
        except Exception as e:
            return inkex.errormsg(
                "Could not write file:\n  {path}\n{err}\n\n"
                "Try entering a full path in the dialog "
                "(e.g. C:\\Users\\YourName\\Desktop\\block.pj6).".format(
                    path=out_path, err=str(e)))

        # Verify it actually got written and report the FULL absolute path
        out_path_abs = os.path.abspath(out_path)
        try:
            written_size = os.path.getsize(out_path_abs)
        except Exception:
            written_size = len(file_bytes)

        inkex.utils.debug(
            "EQ export complete!\n\n"
            "  Saved to:  {path}\n"
            "  File size: {size} bytes\n"
            "  Format:    {fmt}\n"
            "  Lines:     {nl}\n"
            "  Patches:   {np}\n"
            "  Block:     {w:.3f}\" x {h:.3f}\"  ({src})\n\n"
            "To open in EQ8:\n"
            "  File > Open > navigate to the path above and select your file\n"
            "  Block appears in Libraries > Sketchbook".format(
                path=out_path_abs,
                size=written_size,
                fmt=target.upper(),
                nl=len(lines_norm),
                np=patch_count,
                w=block_w_in,
                h=block_h_in,
                src=size_source,
            )
        )

    # ----------------------------------------------------------------------
    # Block-size auto-detection
    # ----------------------------------------------------------------------

    def _detect_block_size_px(self, tree):
        """
        Determine the block's true size in SVG pixels.

        Strategy:
          1. Collect every leaf-region vertex.
          2. The block's bounding box defines its size — block geometry
             always extends to the full extent (corner vertices exist).
          3. Cross-check against <svg width=...> if available.

        Returns (width_px, height_px) or (None, None) if undetectable.
        """
        all_x, all_y = [], []
        for r in tree.regions.values():
            if r.children:
                continue
            for x, y in r.polygon:
                all_x.append(float(x))
                all_y.append(float(y))

        if not all_x:
            return (None, None)

        min_x, max_x = min(all_x), max(all_x)
        min_y, max_y = min(all_y), max(all_y)

        # The polygon coordinates are expected to start at (0, 0) in the
        # block-local space. If they don't, the block geometry is offset
        # in unexpected ways — refuse to auto-detect.
        if min_x < -1.0 or min_y < -1.0:
            return (None, None)

        # Round to nearest whole pixel to avoid floating-point fuzz.
        block_w = round(max_x)
        block_h = round(max_y)

        if block_w <= 0 or block_h <= 0:
            return (None, None)

        # Optional cross-check against SVG width/height.
        svg_w = self._svg_dim(self.svg.get("width"))
        svg_h = self._svg_dim(self.svg.get("height"))
        if svg_w and abs(svg_w - block_w) > 2:
            # Geometry's bounding box doesn't match SVG canvas — trust the
            # geometry, but flag in case the user expected otherwise.
            pass
        if svg_h and abs(svg_h - block_h) > 2:
            pass

        return (block_w, block_h)

    @staticmethod
    def _svg_dim(s):
        """Parse an SVG width/height string like '576.0px' to a float."""
        if not s:
            return None
        s = s.strip().lower()
        for suffix in ("px", "pt", "pc", "mm", "cm", "in", "em", "ex"):
            if s.endswith(suffix):
                s = s[:-len(suffix)]
                break
        try:
            return float(s)
        except ValueError:
            return None

    # ----------------------------------------------------------------------
    # Path helpers
    # ----------------------------------------------------------------------

    @staticmethod
    def _get_documents_dir():
        """
        Best-effort resolution of the user's Documents folder.
        Falls back to the home directory, and finally to current working dir.
        """
        # Windows: try the Documents shell folder via env vars first
        userprofile = os.environ.get("USERPROFILE")
        if userprofile:
            candidate = os.path.join(userprofile, "Documents")
            if os.path.isdir(candidate):
                return candidate
            # Some users have it as 'My Documents'
            candidate = os.path.join(userprofile, "My Documents")
            if os.path.isdir(candidate):
                return candidate
            return userprofile

        # macOS / Linux
        home = os.path.expanduser("~")
        candidate = os.path.join(home, "Documents")
        if os.path.isdir(candidate):
            return candidate
        if os.path.isdir(home):
            return home

        return os.getcwd()

    @staticmethod
    def _sanitise_filename(name):
        """Strip path separators and characters that are invalid on Windows."""
        bad = '<>:"/\\|?*'
        out = "".join(c if c not in bad else "_" for c in name)
        out = out.strip(" .")
        return out or "fpp_block"


if __name__ == "__main__":
    EQExportPlugin().run()
